apiVersion: v1
data:
  DB_HOST: "db" 
  DB_PORT: "5432"
  ODOO_SESSION_REDIS: "1" 
  ODOO_SESSION_REDIS_HOST: "redis"
  ODOO_SESSION_REDIS_PORT: "6379"
  ODOO_SESSION_REDIS_PREFIX: "odoo:prod"
  ODOO_SESSION_REDIS_EXPIRATION: "604800"
  ODOO_SESSION_REDIS_EXPIRATION_ANONYMOUS: "86400"
  LIMIT_MEMORY_HARD: "1073741824"
  LIMIT_MEMORY_SOFT: "805306368"
  LIMIT_REQUEST: "320000"
  LIMIT_TIME_CPU: "360000"
  LIMIT_TIME_REAL: "720000"
kind: ConfigMap
metadata:
  name: sysmarket-configmap
  namespace: development
