apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postrgres
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
