apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysmarket
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysmarket
  template:
    metadata:
      labels:
        app: sysmarket
    spec:
      imagePullSecrets:
        - name: gitlab-secret
      initContainers:
        - name: wait-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z db 5432; do
                echo "waiting for postgres"
                sleep 2
              done

        - name: wait-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z redis 6379; do
                echo "waiting for redis"
                sleep 2
              done
      securityContext:
        runAsUser: 996
        runAsGroup: 994
        runAsNonRoot: true
      containers:
        - name: sysmarket
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: registry.gitlab.com/santiagofreiree/sysmarket/sysmarket-redis-srv:v1.8.12.2
          command:
            - /bin/bash
            - -c
          args:
            - |
              # Create the configuration directory and file dynamically
              #              mkdir -p /etc/conf
              cat > /etc/conf/odoo-server.conf << CONFIGEOF
              [options]
              admin_passwd = ${ADMIN_PASSWORD}
              db_host = db
              db_port = 5432
              db_user = ${DB_USER}
              db_password = ${DB_PASSWORD}
              addons_path = /opt/odoo/addons,/opt/addons-odoo
              without-demo=all
              no-xmlrpc = True
              no-xmlrpcs = True
              no-netrpc = True
              log_db = False
              log_handler = ['[\'["[\\\':INFO\\\']"]\']']
              log_level = info
              login_message = False
              logrotate = False
              syslog = False
              limit_memory_hard = ${LIMIT_MEMORY_HARD}
              limit_memory_soft = ${LIMIT_MEMORY_SOFT}
              limit_request = ${LIMIT_REQUEST}
              limit_time_cpu = ${LIMIT_TIME_CPU}
              limit_time_real = ${LIMIT_TIME_REAL}
              max_cron_threads = 1
              workers = 2
              longpolling_port = 8072
              xmlrpc_port = 8070
              proxy_mode = True
              data_dir = /var/lib/odoo
              CONFIGEOF
              /usr/bin/python /opt/odoo/openerp-server --config /etc/conf/odoo-server.conf -d dula01
#              su - odoo -c '/usr/bin/python /opt/odoo/openerp-server --config /etc/conf/odoo-server.conf -d dula01'

          ports:
            - containerPort: 8070
              name: http
            - containerPort: 8072
              name: longpolling
          envFrom:
            - configMapRef:
                name: sysmarket-configmap
          env:
            - name: ODOO_SESSION_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASSWORD
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: POSTGRES_PASSWORD
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sysmarket-secrets
                  key: ADMIN_PASSWORD
          volumeMounts:
            - name: odoo-temp
              mountPath: /var/lib/odoo
            - name: odoo-conf
              mountPath: /etc/conf
      volumes:
        - name: odoo-temp
          emptyDir: {}
        - name: odoo-conf
          emptyDir: {}



